#!/usr/bin/env node
/*global process, require*/
/* vim: set syntax=javascript: */
var
	gravity = require('./gravity.js'),

	// Parse command line args
	args = (function (argv) {
		var
			len = argv.length,
			command = len > 2 && argv[2],
			dir = len > 3 && argv[3],
			arg4 = len > 4 && argv[4],
			lastArg = arg4 || dir,
			slash = dir && (dir.length - 1),
			args = {},
			hostPort
		;

		if (command === 'version' || command === 'serve' || command === 'build') {
			console.log('gravity version ' + gravity.VERSION);
			if (command === 'version') {
				process.exit(0);
			}
		}

		if (len < 3 ||
			(command !== 'serve' && command !== 'get' && command !== 'build') ||
			(command === 'get' && len < 4) ||
			(command === 'build' && len < 4))
		{
			console.log('Usage:');
			console.log('  gravity build <dir> <outdir>');
			console.log('    or');
			console.log('  gravity get <dir> <path>');
			console.log('    or');
			console.log('  gravity serve <dir> [[<host>]:[<port>]]');
			process.exit(1);
		}

		args.serve = command === 'serve';
		args.get = command === 'get';
		args.build = command === 'build';
		args.dir = dir.charAt(slash) === '/' ? dir.substr(0, slash) : dir;

		if (args.serve) {
			hostPort = (arg4 || ':').split(':');
			args.host = hostPort[0];
			args.port = hostPort[1];
		}

		if (args.get) {
			args.path = lastArg;
		}

		if (args.build) {
			args.outDir = lastArg;
		}

		return args;
	}(process.argv)),

	baseDir = args.dir,

	// Gravity Map
	gravMapFileName = 'gravity.map',
	gravMapFilePath = baseDir + '/' + gravMapFileName,

	// Server args
	defaultHost = '127.0.0.1',
	defaultPort = 1337,
	serverHost = args.host || defaultHost,
	preferredPort = args.port || defaultPort,

	// Build args
	outDir = args.outDir
;


if (args.serve) {
	gravity.serve(gravMapFilePath, baseDir, serverHost, preferredPort);
}


if (args.get) {
	gravity.pull(gravMapFilePath, baseDir, args.path, function (err, content) {
		if (content) {
			console.log(content + '');
		}
	});
}


if (args.build) {
	gravity.build(gravMapFilePath, baseDir, outDir, function (err) {
		if (err) {
			console.log('gravity.build() error:', err);
		} else {
			console.log('Done.');
		}
	});
}
