#!/usr/bin/env node
/*global process, require*/
var
	gravity = require('./gravity.js'),

	// Parse command line args
	args = (function (argv) {
		var
			len = argv.length,
			command = len > 2 && argv[2],
			arg3 = len > 3 && argv[3],
			arg4 = len > 4 && argv[4],
			expectedLengths = { build: 5, get: 5, list: 4, pull: 5, serve: 5 },
			expectedLen = expectedLengths[command],
			isExpectedLen = len === expectedLen,
			dir = isExpectedLen ? arg3 : '.',
			lastArg = isExpectedLen ? arg4 : arg3,
			slash = dir && (dir.length - 1),
			args = {},
			hostPort,
			badUsage = (len < 2 || len > 5 ||
				(command !== 'build' && command !== 'get' && command !== 'list' &&
					command !== 'pull' && command !== 'serve') ||
				((command === 'get' || command === 'pull') && len < 3) ||
				(command === 'build' && len < 3))
		;

		if (badUsage || command === 'build' || command === 'serve' || command === 'version') {
			console.log('gravity version ' + gravity.VERSION);
			if (command === 'version') {
				process.exit(0);
			}
		}

		if (badUsage) {
			console.log('');
			console.log('Usage:');
			console.log('  gravity build [<map>] <outdir>');
			console.log('    or');
			console.log('  gravity list [<map>]');
			console.log('    or');
			console.log('  gravity pull [<map>] <path>');
			console.log('    or');
			console.log('  gravity serve [<map>] <host>:<port>');
			process.exit(1);
		}

		args.build = command === 'build';
		args.list = command === 'list';
		args.pull = command === 'pull' || command === 'get';
		args.serve = command === 'serve';
		args.dir = dir.charAt(slash) === '/' ? dir.substr(0, slash) : dir;

		if (args.build) {
			args.outDir = lastArg;
		}

		if (args.pull) {
			args.path = lastArg;
		}

		if (args.serve) {
			hostPort = (lastArg || ':').split(':');
			args.host = hostPort[0];
			args.port = hostPort[1];
		}

		return args;
	}(process.argv)),

	baseDir = args.dir,

	// Gravity Map
	gravMapFileName = 'gravity.map',
	gravMapFilePath = baseDir + '/' + gravMapFileName,

	// Server args
	defaultHost = '127.0.0.1',
	defaultPort = 1337,
	serverHost = args.host || defaultHost,
	preferredPort = args.port || defaultPort,

	// Build args
	outDir = args.outDir
;


if (args.serve) {
	gravity.serve(gravMapFilePath, baseDir, serverHost, preferredPort);
}


if (args.list) {
	gravity.list(gravMapFilePath, baseDir, function (err, list) {
		var i = -1, len = list && list.length;
		if (err) {
			console.log(err);
		} else {
			while (++i < len) {
				console.log(list[i]);
			}
		}
	});
}


if (args.pull) {
	gravity.pull(gravMapFilePath, baseDir, args.path, function (err, content) {
		if (content) {
			console.log(content + '');
		}
	});
}


if (args.build) {
	gravity.build(gravMapFilePath, baseDir, outDir, function (err) {
		if (err) {
			console.log('gravity.build() error:', err);
		} else {
			console.log('Done.');
		}
	});
}
